name: Springboot Project Creation

on:
  workflow_dispatch:
    inputs:
      app-name:
        description: 'The is the name of app you want to create'
        required: true
        type: string
      template-app-github-location:
        description: 'Github location of template app'
        required: true
        type: string
        default: 'https://github.com/shakeel85331'
      template-app-name:
        description: 'Template app name'
        required: true
        type: string
        default: 'movie-info-service'
      app-uplaod-github-location:
        description: 'Github location where newly create app needs to get uploaded'
        required: true
        type: string
        default: 'https://github.com/mshakeel-projects'
      app-type:
        description: 'This is the type of app you want to create.'
        required: true
        type: choice
        options:
          - plain_springboot
          - publisher_springboot
          - consumer_springboot
      jira-story:
        description: 'The is the jira story for the app creation'
        required: true
        type: string
        default: 'TEST-0000'
      github-password-token:
        description: 'Github Password Token'
        required: true
        type: string

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Run a script
        run: sh repo_initializer.sh ${{ inputs.app-name}} ${{ inputs.template-app-github-location}} ${{ inputs.template-app-name }} ${{ inputs.app-uplaod-github-location}} ${{ inputs.jira-story}} ${{ inputs.app-type}} ${{ github.actor }} ${{ inputs.github-password-token}} ${{ github.actor_id }}+${{ github.actor }}@users.noreply.github.com
